import LocalizedStrings from 'react-native-localization';
export const DEFAULT_LANGUAGE = 'en';

const languages = {
  en: {
    Facebook: 'Facebook',
    Google: 'Google',
    Email: 'Email',
    lets_started: "Let's get started",
    ask_email: "What's your email?",
    ask_name: 'What should we call you?',
    create_password: 'Now create a password.',
    got_it: 'ok got it!',
    be: 'Be a',
    other_option: 'Other options',
    hero: 'hero',
    savior: 'Savior.',
    together: `Together let's fight food waste.`,
    choose_country: 'Your country',
    welcome: 'Welcome!',
    from_country: 'Which country are you in?',
    send: 'Send',
    name: 'Name',
    stop_waste: 'and stop food waste',
    social_signin: ' Sign in with Social Media',
    signupemail: 'Sign Up With Email',
    already_account: 'Already Have an Account? ',
    login: 'Login',
    lable_agree: 'I agree with the',
    lable_and: 'and the',
    signin_welcome: 'Welcome Back',
    forgotPassword: 'Forgot Password',
    reset_password: 'Reset Your ',
    askpassword: 'Password?',
    password: 'Password',
    great: 'Great!',
    signin_password: 'And your password?',
    reset_pw: 'Reset Password',
    feel_details: 'Fill below details to reset your password',
    verification_code: 'Verification code',
    continue: 'Continue',
    username: 'Username',
    select_country: 'Please select your country',
    notification: 'Notifications',
    language: 'Language',
    privacy: 'Privacy & licenses',
    privacylicense: 'Privacy & Licenses',
    email_id: 'Email id',
    phone: 'Phone number',
    accountdetails: 'Account Details',
    setting: 'Settings',
    edit: 'Edit',
    pushNotifications: 'Push Notifications',
    emailnewsletter: 'Email newsletter',
    privacypolicy: 'Privacy policy',
    editProfile: 'Edit your profile',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmPassword: 'Confirm Password',
    save: 'Save',
    country: 'Country',
    verify: 'Verify',
    feel_verification_code:
      'Please enter the verification code received by email',
    loading: 'Loading...',
    comingsoon: 'Coming soon...',
    blog_looking: 'Looking for something?',
    looking_for: 'Looking for something..',
    read_about: 'I want to read about',
    help: 'How can we help you?',
    choose_topic: 'Please choose a topic from below',
    myOrder: 'My Order',
    saviour: 'How to Foody Savior Work',
    join_business: 'Join to Foody Savior Business',
    sortby: 'Sort by : ',
    nearby: 'Nearby',
    recommended: 'Recommended For You',
    IngredientsAllergens: 'Ingredients & Allergens',
    profile: 'Profile',
    helpCenter: 'Help Center',
    changePassword: 'Change Password',
    blog: 'Blog',
    termsAndConditions: 'Terms And Conditions',
    licenses: 'Licenses',
    favourite: 'My favorite stores',
    myProfile: 'My profile',
    orders: 'Orders',
    payment: 'Payment methods',
    terms: 'Terms & conditions',
    errorValidPassword:
      'Password should contain one upper case, one lower case, one special character and one numeric value',
    errorUnMatach: 'Password and confirm password should be same',
    errorVerificationCode: 'Please Enter Valid verification Code',
    errorValidPhone: 'Please enter valid phone number',
    errorValidCountry: 'Please select valid country',
    errorInternetConnection: 'Please check your internet connection',
    error_terms: 'Please accept terms & conditions',
    error_valid_email: 'Please enter valid email address',
    error_valid_name: 'Please enter max 20 character',
    stack_Home: 'Home',
    stack_Browse: 'Browse',
    stack_Favourites: 'Favourites',
    stack_More: 'More',
    submit: 'Submit',
    Whatotheraresaying: 'What other are saying',
    PeoplelovethisMagicBag: 'People love this surprise basket',
    peopleMesg: '% rated their purchases at least 4 out of 5 stars.',
    greatService: 'Great service',
    greatServiceMesg: 'People liked the service here.',
    highQuality: 'High quality food',
    highQualityMesg: 'People said the food was hugh quality.',
    goodAmount: 'Good amount',
    goodAmountMesg: 'People were happy with the amount of food they got.',
    goodAmountMesg2: 'Based on 73 ratings over the past month',
    didYouKnow: 'Did you know?',
    didYouKnowMesg:
      '25% of food waste in Canada is produced by shops, restaurants and hotels',
    direction: 'Directions',
    reserve: 'Reserve',
    btnReserve: 'RESERVE',
    gotIt: 'GOT IT!',
    magicBag: 'Your basket is a surprise',
    surprise: 'surprise',
    surpriseMsg: `We cannot predict what will be in your surprise basket as it depends on the day's surplus. If you have any questions about allergens or ingredients, ask the store.`,
    selectQty: 'Select quantity',
    total_: 'Total £',
    reservingMesg: 'By reserving this meal you agree to',
    reserveNow: 'RESERVE NOW',
    whatYouCouldGo: 'What you could get',
    collectMagicBag: "Your merchant's adress",
    toGos: `FoodySavior's `,
    order: 'Order',
    btnOrder: 'ORDER',
    msgLocation: 'Please wait we are fetching your location...',
    dateAll: 'All',
    apply: 'Apply',
    clear: 'Clear',
    allDay: 'All day',
    empty_current_order: 'No Current Order',
    empty_past_order: 'No Past Order',
    empty_order_desc: "Orders that haven't been collected yet are here",
    lable_current: 'Current',
    lable_past: 'Past',
    error_unable_fetch: 'Unable to fetch your current location',
    no_location_name: 'No Name',
    empty_data: 'No data found',
    lable_select_distance: 'Select distance',
    lable_selected_area: "We'll show you stores within the selected area.",
    lable_your_location: 'Your location',
    error_something_wrong: 'Something went wrong',
    orderMessage: 'Thank you for ordering.',
    receivedOrder: 'We received your order.',
    ok: 'Ok',
    lable_search_location: 'Search Location',
    lable_canada: 'Canada',
    lable_usa: 'USA',
    label_search_for_city: 'Search for city',
    lable_resend_otp: 'Resend the verification code',
    lable_hello: 'Hello',
    location_alert: 'App needs permission to access your location',
    setting_cancel: 'Cancel',
    card: ' Card ',
    star: ` **** **** **** `,
    default: 'Default',
    setAsDefault: 'Set as default',
    msgDeleteCard: 'Are you sure you want to delete this card ?',
    yes: 'Yes',
    no: 'No',
    msgSetAsDefault: 'Are you sure you want to make this card as default ?',
    msgCollectionTime: `It's look like your collection time is closed.`,
    category: 'Category',
    dietPreferences: 'Diet preferences',
    collectionTime: 'Collection time',
    hideSoldOut: 'Hide sold out',
    storeName: 'Store name',
    hintStore: 'Enter store name...',
    cleartAll: 'Clear all',
    location: 'Location',
    filter: 'Filter',
    hideSoldOutNote:
      'Most stores only have a limited amount of surprise baskets for sale every day. By activating this filter, we willl only show you stores with food left to save today.',
    lable_diet_none: 'None',
    lable_from: 'From',
    lable_to: 'To',
    lable_diet_nonveg: 'Non-Vegetarian',
    lable_diet_veg: 'Vegetarian',
    lable_diet_halla: 'Halal',
    lable_diet_bio: 'Bio',
    lable_diet_vegan: 'Vegan',
    lable_diet_casher: 'Casher',
    lable_diet_sans: 'Sans gluten',

    title_order_detail: 'Your Reservation',
    lable_click_here_to_view_detail: 'Click here to see them!',
    lable_booking_status: 'Status of Reservation',
    lable_toget_back: 'To be picked up',
    lable_reserve_number: 'Reservation number',
    lable_outdoor_plant: 'Outdoor plants',
    lable_collect: 'Pickup Details',
    label_and: 'and',
    lable_need_help: 'Need help?',
    lable_collect_collection: 'Click to collect your basket',
    lable_experience: 'We are glad you had a good experience',
    lable_what_prefer: 'What did you prefer?',
    review_sufficient_product_value: 'Sufficient product value',
    review_good_product_amount: 'Good amount of products',
    review_good_product: 'Good products',
    review_friendly_team: 'Friendly team',
    review_product_verity: 'Good variety of products',
    lable_note_basket: 'RATE YOUR BASKET',
    lable_validate_note: 'VALIDATE MY NOTE',
    lable_your_experience: 'How was your experience?',
    lable_collection_start: 'The collection starts in',
    lable_reservation_here: 'Anti-waste mission launched!', //'Your reservation is here',
    lable_click_latest_order:
      'Your basket can be picked up within the indicated collection time slot! Please find more details below.', //'Click here to see your receipt and validate it with merchant during your pick up',
    lable_success_feedback:
      'Great ! We are delighted to know that you have enjoyed your anti-waste mission. Do not hesitate to rate us on the',
    lable_thankyou: 'Thank you',
    lable_rate_us: 'Rate Us',
    lable_not_now: 'Not now',
    lable_validate_order_detail:
      'Validate below and show your screen to merchant. Make sure to confirm your order only when you are at the store to be able to pickup your basket.',
    lable_orderto_pickup: 'Order to pick up',
    label_left: 'left',
    label_list: 'List',
    label_map: 'Map',
    label_current_location: 'Current location',
    chooseLocation: 'Choose Location',
    label_card_number: 'Card Number',
    label_month: 'MM/YYYY',
    label_cvv: 'CVV',
    label_cardHolder: 'Card Holder Name',
    label_saveCard: 'Save Card',
    label_savedCard: 'Saved Card',
    label_addCard: 'Add New Card',
    label_enterCard: 'Enter Card Details',
    error_valid_card_number: 'Please enter valid card number',
    error_valid_month: 'Please enter valid month',
    error_valid_year: 'Please enter valid year',
    error_valid_cvv: 'Please enter valid cvv',
    error_invalid_card_number: "Your card's number is invalid",
    label_total: 'Total',
    label_between: 'between',
    lable_write_experience: 'Your comment...',
    error_select_review: 'Please select at least one answer',
    lable_order_date: 'Order Date',
    error_select_ratings: 'Please rate your experience',
    error_write_review: 'Please enter comment',
    error_valid_data: 'Please enter valid data',
    lable_done: 'Done',
    msgCancelOrder: 'Are you sure you want to cancel this order?',
    msgLogout: 'Are you sure you want to exit?',
    titleAccessLocation: 'We need to access your location',
    msgAccessLocation: 'We use your location to show where you are on the map',
    msgPlaceOrder: 'Please wait for the collection time to start.',
    alert_retrieve: 'Retrieve',
    updateAvailable: 'Update Available',
    newVersion: 'A new version of Foody Savior is available. Please update now',
    update: 'Update',
    urlNotAvaiable: 'URL not available, Please update the app manually.',
    ImpInfo: 'Important Information',
    contact_us: 'Contact Us',
    lable_basket: 'Basket',
    choose_lang: 'Choose language',
    logout: 'Logout',
    lable_subtotal: 'Subtotal',
    tpsTax: 'TPS Tax',
    tvpTax: 'TVP Tax',
    tvhTax: 'TVH Tax',
    tvqTax: 'TVQ Tax',
    refunded: 'Refunded',
    label_defaultcard: 'Set Default',
    you_will_stop: `Are you sure you don't want to receive any push notifications?`,
    you_will_receive: `Are you sure you want to receive all push notifications?`,
    placed: 'Placed',
    delivered: 'Delivered',
    cancelled: 'Cancelled',
    notPickup: 'Not Picked Up',
  },
  fr: {
    Facebook: 'Facebook',
    Google: 'Google',
    Email: 'Courriel',
    lets_started: 'Commençons',
    ask_email: 'Quel est votre courriel ?',
    ask_name: 'Comment devrions-nous vous appeler ?',
    create_password: 'Créez votre mot de passe.',
    got_it: "C'est compris",
    be: 'Soyez un',
    other_option: 'Autres options',
    hero: 'héros',
    savior: 'Sauveur.',
    together: 'Ensemble luttons contre le gaspillage alimentaire.',
    choose_country: 'Votre pays',
    welcome: 'Bienvenue!',
    from_country: 'Dans quel pays êtes vous ?',
    send: 'Valider',
    name: 'Nom',
    stop_waste: 'et arrêtez le gaspillage alimentaire',
    social_signin: ' Connectez-vous avec les médias sociaux',
    signupemail: "S'enregistrer avec l'adresse e-mail",
    already_account: 'Avez-vous déjà un compte ? ',
    login: "S'identifier",
    lable_agree: `Je suis d'accord avec le`,
    lable_and: 'et le',
    signin_welcome: 'Bon retour',
    forgotPassword: 'Mot de passe oublié',
    reset_password: 'Réinitialiser votre mot de passe ',
    askpassword: 'Mot de passe?',
    password: 'Mot de passe',
    great: 'Génial!',
    signin_password: 'Et votre mot de passe?',
    reset_pw: 'Réinitialiser votre mot de passe',
    feel_details:
      'Remplissez les détails ci-dessous pour réinitialiser votre mot de passe',
    verification_code: 'Code de vérification',
    continue: 'Continuer',
    username: "Nom d'utilisateur",
    select_country: 'Merci de sélectionner votre pays',
    notification: 'Notifications',
    language: 'Langue',
    privacy: 'Confidentialité et licences',
    privacylicense: 'Confidentialité et mentions légales',
    email_id: 'Identifiant de messagerie',
    phone: 'Numéro de téléphone',
    accountdetails: 'Détails du compte',
    setting: 'Paramètres',
    edit: 'Modifier',
    pushNotifications: 'Notifications push',
    emailnewsletter: 'Courriel',
    privacypolicy: 'Politique de confidentialité',
    editProfile: 'Modifier votre profil',
    currentPassword: 'Mot de passe actuel',
    newPassword: 'Nouveau mot de passe',
    confirmPassword: 'Confirmez le mot de passe',
    save: 'Enregistrer',
    country: 'Pays',
    verify: 'Vérifier',
    feel_verification_code:
      'Merci de renseigner le code de vérification reçu par courriel',
    loading: 'Chargement...',
    comingsoon: 'Bientôt disponible...',
    blog_looking: 'Vous cherchez quelque chose?',
    looking_for: 'Vous cherchez quelque chose ...',
    read_about: 'Je veux en savoir plus',
    help: 'Comment pouvons-nous vous aider?',
    choose_topic: 'Choisissez un theme ci dessous',
    myOrder: 'Ma commande',
    saviour: 'Comment travailler avec Foody Savior',
    join_business: "Rejoignez l'entreprise Foody Savior",
    sortby: 'Trier par :',
    nearby: 'Proche',
    recommended: 'Recommandé pour vous',
    profile: 'Profil',
    helpCenter: "Centre d'aide",
    changePassword: 'Changer le mot de passe',
    blog: 'Blog',
    termsAndConditions: 'Termes et conditions',
    licenses: 'Mentions légales',
    favourite: 'Mes commerces favoris',
    myProfile: 'Mon profil',
    orders: 'Commandes',
    payment: 'Méthodes de paiement',
    terms: 'Termes et conditions',
    errorValidPassword:
      'Le mot de passe doit contenir une majuscule, une minuscule, un caractère spécial et une valeur numérique',
    errorUnMatach: 'Les mots de passe doivent être identiques',
    errorVerificationCode: 'Merci de saisir un code de vérification valide',
    errorValidPhone: 'Merci de saisir un numéro de téléphone valide',
    errorValidCountry: 'Merci de sélectionner un pays valide',
    errorInternetConnection: 'Merci de vérifier votre connexion internet',
    error_terms: "Merci d'accepter les termes et conditions",
    error_valid_email: 'Merci de saisir un courriel valide',
    error_valid_name: 'Merci de saisir 20 caractères maximum',
    stack_Home: 'Accueil',
    stack_Browse: 'Explorer',
    stack_Favourites: 'Favoris',
    stack_More: 'Plus',
    submit: 'Envoyer',
    IngredientsAllergens: 'Ingrédients & Allergènes',
    Whatotheraresaying: 'Que disent les autres',
    PeoplelovethisMagicBag: 'Les gens adorent ce panier surprise',
    peopleMesg: '% ont évalué leurs achats à au moins 4 étoiles sur 5.',
    greatService: 'Très bon service',
    greatServiceMesg: 'Les gens ont aimé le service ici.',
    highQuality: 'Nourriture de bonne qualité',
    highQualityMesg: 'Les gens ont dit que la nourriture était excellente.',
    goodAmount: 'BONNES QUANTITÉS',
    goodAmountMesg: `Les gens étaient satisfaits de la quantité de nourriture qu'ils recevaient.`,
    goodAmountMesg2: 'Sur la base de 73 notes le mois dernier',
    didYouKnow: 'Le saviez-vous?',
    didYouKnowMesg:
      '25% du gaspillage alimentaire au Canada est généré par les commerces, restaurants et hotels',
    direction: 'itinéraire',
    reserve: 'réserve',
    btnReserve: 'RÉSERVER',
    gotIt: `COMPRIS`,
    magicBag: 'Votre panier est surprise',
    surprise: 'surprise',
    surpriseMsg: `Nous ne pouvons pas prédire ce qui sera dans votre panier surprise car celà dépend des surplus du jour. Si vous avez des interrogations sur les allergènes ou les ingrédients, demandez au commerçant. `,
    selectQty: 'Sélectionnez la quantité',
    total_: 'Total £',
    reservingMesg: 'En réservant ce repas vous acceptez',
    reserveNow: 'RÉSERVEZ MAINTENANT',
    whatYouCouldGo: 'Ce que vous pourriez obtenir',
    collectMagicBag: 'Adresse de votre commerçant',
    toGos: `FoodySavior's `,
    order: 'Ordre',
    btnOrder: 'COMMANDER',
    msgLocation: 'Merci de patienter, nous récupérons votre position...',
    dateAll: 'Tout',
    apply: 'Appliquer',
    clear: 'Effacer',
    allDay: 'Toute la journée',
    empty_current_order: 'Aucune commande en cours',
    empty_past_order: 'Aucune commande passée',
    empty_order_desc:
      "Les commandes qui n'ont pas encore été collectées se trouvent ici",
    lable_current: 'Actuelle',
    lable_past: 'Passée',
    error_unable_fetch: 'Impossible de récupérer votre position',
    no_location_name: 'Sans nom',
    empty_data: 'Aucune donnée disponible',
    lable_select_distance: 'Sélectionnez la distance',
    lable_selected_area:
      'Nous vous montrerons les magasins dans la zone sélectionnée.',
    lable_your_location: 'Votre emplacement',
    error_something_wrong: 'Un problème est survenu',
    orderMessage: `Merci d'avoir commandé.`,
    receivedOrder: 'Nous avons bien reçu votre commande.',
    ok: `D'accord`,
    lable_search_location: 'Rechercher un emplacement',
    lable_canada: 'Canada',
    lable_usa: 'Etats-Unis',
    label_search_for_city: 'Rechercher une ville',
    lable_resend_otp: 'Renvoyer le code de vérification',
    lable_hello: 'Bonjour',
    location_alert:
      "L'application a besoin d'une autorisation pour accéder à votre position",
    setting_cancel: 'Annuler',
    card: 'Carte',
    star: ` **** **** **** `,
    default: 'Défaut',
    setAsDefault: 'Définir par défaut',
    msgDeleteCard: 'Voulez-vous vraiment supprimer cette carte?',
    yes: 'Oui',
    no: 'Non',
    msgSetAsDefault: 'Voulez-vous vraiment utiliser cette carte par défaut?',
    msgCollectionTime: `Il semble que votre heure de collecte soit clôturée.`,
    category: 'Catégorie',
    dietPreferences: 'Préférences alimentaires',
    collectionTime: 'Heure de collecte',
    hideSoldOut: 'Masquer épuisé',
    storeName: 'Nom du magasin',
    hintStore: 'Entrez le nom du magasin...',
    cleartAll: 'Tout effacer',
    location: 'Emplacement',
    filter: 'Filtres',
    hideSoldOutNote:
      "La plupart des magasins n'ont qu'une quantité limitée de paniers surprises à vendre chaque jour. En activant ce filtre, nous ne vous montrerons que les magasins ayant des panniers disponibles aujourd'hui.",
    lable_diet_none: 'Aucun',
    lable_from: 'De',
    lable_to: 'À',
    lable_diet_nonveg: 'Non végétarien',
    lable_diet_veg: 'Végétarien',
    lable_diet_halla: 'Halal',
    lable_diet_bio: 'Bio',
    lable_diet_vegan: 'Vegan',
    lable_diet_casher: 'Casher',
    lable_diet_sans: 'Sans gluten',

    title_order_detail: 'Votre réservation',
    lable_click_here_to_view_detail: 'Cliquez ici pour les voir!',
    lable_booking_status: 'STATUT DE LA RÉSERVATION',
    lable_toget_back: 'À récupérer',
    lable_reserve_number: 'Numéro de réservation',
    lable_outdoor_plant: 'Plantes extérieures',
    lable_collect: 'Collecte',
    label_and: 'et',
    lable_need_help: "Besoin d'aide ?",
    lable_collect_collection: 'Cliquez pour récupérer votre panier',
    lable_experience: 'Nous sommes ravis que vous ayez eu une bonne expérience',
    lable_what_prefer: "Qu'avez-vous préféré?",
    lable_note_basket: 'NOTEZ VOTRE PANIER',
    lable_validate_note: 'VALIDER MA NOTE',
    lable_your_experience: "Comment s'est passée votre expérience ?",
    review_sufficient_product_value: 'Valeur des produits suffisante',
    review_good_product_amount: 'Bonne quantité de produits',
    review_good_product: 'Bons produits',
    review_friendly_team: 'Équipe sympathique',
    review_product_verity: 'Bonne variété de produits',
    lable_collection_start: 'La collecte démarre dans',
    lable_reservation_here: 'Mission Anti-gaspillage enclenchée!', //'Votre réservation est ici',
    lable_click_latest_order:
      'Le panier pourra être récupéré dans la tranche d’heure de collecte indiquée! Veuillez trouver ci dessous plus de détails.', //'Cliquez ici pour voir votre reçu et le valider auprès du marchand lors de votre prise en charge',
    lable_success_feedback:
      "Super ! Nous sommes ravis de savoir que vous avez apprécié votre misson anti-gaspillage. N'hésitez pas à nous noter sur le",
    lable_thankyou: 'Merci',
    lable_rate_us: 'Nous Noter',
    lable_not_now: 'Pas Maintenant',
    lable_validate_order_detail:
      'Validez ci-dessous et montrez votre écran au marchand. Assurez-vous de ne confirmer votre commande que lorsque vous êtes au magasin pour pouvoir récupérer votre panier.',
    lable_orderto_pickup: 'Commande à récupérer',
    label_left: 'panier restant',
    label_list: 'liste',
    label_map: 'Carte',
    label_current_location: 'Localisation actuelle',
    chooseLocation: 'Choisissez un emplacement',
    label_card_number: 'Numéro de carte',
    label_month: 'MM/AAAA',
    label_cvv: 'CVV',
    label_cardHolder: 'Nom du titulaire',
    label_saveCard: 'Enregistrer la carte',
    label_savedCard: 'Carte enregistrée',
    label_addCard: 'Ajouter une nouvelle carte',
    label_enterCard: 'Entrez les détails de la carte',
    error_valid_card_number: 'Merci de saisir un numéro de carte valide',
    error_valid_month: 'Merci de saisir un mois valide',
    error_valid_year: 'Merci de saisir une année valide',
    error_valid_cvv: 'Merci de saisir un cvv valide',
    error_invalid_card_number: "Votre numéro de carte n'est pas valide",
    label_total: 'Total',
    label_between: 'entre',
    lable_write_experience: 'Votre commentaire...',
    error_select_review: 'Merci de sélectionner au moins une réponse',
    lable_order_date: 'Date de commande',
    error_select_ratings: 'Merci de noter votre expérience',
    error_write_review: 'Merci de saisir un commentaire',
    error_valid_data: 'Merci de saisir des données valides',
    lable_done: 'Terminé',
    msgCancelOrder: 'Êtes-vous sûr de vouloir annuler cette commande',
    msgLogout: 'Êtes-vous sûr de vouloir quitter?',
    titleAccessLocation: 'Nous devons accéder à votre position',
    msgAccessLocation:
      'Nous utilisons votre emplacement pour indiquer où vous vous trouvez sur la carte',
    msgPlaceOrder: 'Veuillez attendre le début de l’heure de collecte',
    alert_retrieve: 'Récupérer',
    updateAvailable: 'Mise à jour disponible',
    newVersion: `Une nouvelle version de FoodySavior est disponible. Mettez l'application à jours.`,
    update: 'Mettre à jour',
    urlNotAvaiable:
      "URL non disponible, merci de mettre à jour l'application manuellement.",
    ImpInfo: 'Information Importante',
    contact_us: 'Contact Us',
    lable_basket: 'Panier',
    choose_lang: 'Choisissez la langue',
    logout: 'Se déconnecter',
    lable_subtotal: 'Sous-total',
    tpsTax: 'TPS Taxe',
    tvpTax: 'TVP Taxe',
    tvhTax: 'TVH Taxe',
    tvqTax: 'TVQ Taxe',
    refunded: 'Refunded',
    label_defaultcard: 'Définir par defaut',
    you_will_stop:
      'Êtes-vous sûr de ne pas vouloir recevoir de notifications push?',
    you_will_receive: `Voulez-vous vraiment recevoir toutes les notifications push?`,
    placed: 'Placée',
    delivered: 'Livrée',
    cancelled: 'Annulée',
    notPickup: 'Pas de ramassage',
  },
};
export default new LocalizedStrings(languages);
