const constant = {
    ALERT: 'ALERT',
    ASK_ALERT: 'ASK_ALERT',
    DELETE_CARD_ALERT: 'DELETE_CARD_ALERT',
    DEFAULT_CARD_ALERT: 'DEFAULT_CARD_ALERT',
    LOCATION_ALERT: 'LOCATION_ALERT',
    UNABLE_LOCATION_ALERT: 'UNABLE_LOCATION_ALERT',
    DIET_CATEGORY: 'Category',
    DIET_CATEGORY_FR: 'Catégorie',
    DEIT_ALL: 'All',
    DIET_ALL_FR: 'Tout',
    DIET_PREFERENCE: 'Diet preferences',
    DIET_PREFERENCE_FR: 'Préférences alimentaires',
    DIET_NONE: 'None',
    DIET_NONE_FR: 'Aucun',
    DIET_COLLECTION_TIME: 'Collection time',
    DIET_COLLECTION_TIME_FR: 'Heure de collecte',
    DIET_ALL_DAY: 'All day',
    DIET_ALL_DAY_FR: 'Toute la journée',
    DIET_HIDE_SOLD_OUT: 'Hide sold out',
    DIET_HIDE_SOLD_OUT_FR: 'Masquer épuisé',
    storeName: 'Store name',
    storeName_FR: 'Nom du magasin',
    DIET_LOCATION: 'Location',
    DIET_LOCATION_FR: 'Emplacement',
    NO_HIDESOLD: 'No',
    NO_HIDESOLD_FR: 'Non',
    YES_HIDESOLD: 'Yes',
    YES_HIDESOLD_FR: 'Oui',
  
    REFUNDED: 'REFUNDED',
  
    DIET_VEG: 'Végétarien',
    DIET_BIO: 'Bio',
    DIET_VEGAN: 'Vegan',
    DIET_HALLAL: 'Hallal',
    DIET_KOSHER: 'Casher',
    DIET_SANS: 'Sans gluten',
  
    TPS_TAX: 'tpsTax',
    TVP_TAX: 'tvpTax',
    TVH_TAX: 'tvhTax',
    TVQ_TAX: 'tvqTax',
  
    ERROR_UNKNOWN: 'unknown',
    COLLECTIONTIME_FROM: '',
    COLLECTIONTIME_TO: '',
    AUTH_STACK: 'Auth',
    HOME_STACK: 'Home',
    SCREEN_INTRO: 'INTRO',
    CURRENCY_: '£',
    CURRENCY: '$',
    DATE_FORMAT: 'DD MMMM YYYY',
    ADD_CARD_FORMAT: 'MM/YYY',
  
    TIME_FORMAT: 'HH:mm:ss',
    ORDER_FORMAT: 'DD MMMM',
    TIME_FORMAT_hhmma: 'hh:mm a',
  
    CURRENT_ORDER: 'current',
    PAST_ORDER: 'past',
    PLACED_ORDER: 'Placed',
    DELIVERED_ORDER: 'Delivered',
    CANCELLED_ORDER: 'Cancelled',
    NOT_PICKUP: 'Not Pickup',
  
    CARD_VISA: 'Visa',
    CARD_MASTERCARD: 'MasterCard',
    CARD_AMERICAN: 'American Express',
    CARD_DINERS: 'Diners Club',
    CARD_DISCOVER: 'Discover',
    CARD_JCB: 'JCB',
    CARD_UNIONPAY: 'UnionPay',
    CANADA: 'CA',
    USA: 'US',
    LANG_ENGLISH: 'en',
    LANG_FRENCH: 'fr',
    WEB_CLIENTID:
      '926869527140-e4tdj3j9knb9fpqbfli0dvn8j6u9r1o2.apps.googleusercontent.com', //'57730447051-2n07a4239frmcccmmseur1dciijpa6p9.apps.googleusercontent.com',
    STRIPE_KEY:
      'pk_test_51HWQKZF27rZMkoHW9HcFlsjIRX4MvcDKhOEt7CflUQTVxfNycioeH8yQVOpucTcr8ZUQ2Z3iZfSkeFNH8RVvUy2W00zvGg7fly',
    SETTING_URL: 'app-settings://FoodySavior',
    PAGE_TERMS: 'terms',
    PAGE_PRIVACY: 'privacy',
    LATITUDE_DELTA_18: 1.8,
    LATITUDE_DELTA_099: 0.99,
    LATITUDE_DELTA_19: 0.19999971003482,
    LATITUDE_DELTA_066: 0.66,
    LATITUDE_DELTA_033: 0.33,
    LATITUDE_DELTA_022: 0.22,
    LATITUDE_DELTA_00922: 0.0922,
    LATITUDE_DELTA_00421: 0.0421,
    LOCATION_RADIUS_3: 3,
    LOCATION_RADIUS_5: 5,
    LOCATION_RADIUS_10: 10,
    LOCATION_RADIUS_15: 15,
    LOCATION_RADIUS_30: 30,
    INITIAL_LATITUDE: 0.972,
    INITIAL_LONGITUDE: 0.662,
    INTIALRADIUS: 30,
    LANGUAGE_ENGLISH: 'English',
    LANGUAGE_FRENCH: 'French',
    LANGUAGE_FRENCH_FR: 'Français',
    CANCELLED_ORDER_CODE: 400,
  
    keyAllConstant: {
      isAppFirstTime: 'isAppFirstTime',
      isProfileUpdated: 'isProfileUpdated',
      userToken: 'userToken',
      userFcmToken: 'userFcmToken',
      userLang: 'userLang',
      userLocation: 'userLocation',
      appName: 'FoodySavior',
      deviceId: 'deviceId',
      orderId: 'orderId',
      notification: 'notification',
      currentOrders: 'currentOrders',
      radius: 'radius',
    },
  
    font: {
      poppinsBold: 'Poppins-Bold',
      poppinsLight: 'Poppins-Light',
      poppinsMedium: 'Poppins-Medium',
      poppinsRegular: 'Poppins-Regular',
      poppinsSemiBold: 'Poppins-SemiBold',
      poppinsThinItalic: 'Poppins-ThinItalic',
      poppinsExtraBold: 'Poppins-ExtraBold',
      poppinsItalic: 'Poppins-Italic',
    },
  
    api: {
      registerApi: 'accounts:signUp?key=AIzaSyByFBAg4JoIZ7s_bjG0y02rK8WR-TpNmMY',
      collectionApi:'Collection_Page.json',
      loginApi: 'accounts:signInWithPassword?key=AIzaSyByFBAg4JoIZ7s_bjG0y02rK8WR-TpNmMY',
      countryApi:'country_list.json',
      allReaturantApi: 'allresturats_Information.json',
      favouriteApi:'favouritescreen.json'
    },
  };
  
  export default constant;
  